### ISSUE TITLE
inode_init_owner now handle idmapped mount 

### ISSUE THREAD

**Issue by infus38** [rgouicem/ouichefs#12]
Since release 5.12 (and the following [commit](https://lore.kernel.org/all/20210121131959.646623-7-christian.brauner@ubuntu.com/)), inode_init_owner() now require parsing the initial user namespace, which lead the count to 4 parameters.

**Comment by infus38** [comment]
I created a PR to address this issue.

**Comment by rgouicem** [comment]
We didn't merge that at the time because we needed to keep the kernel version stable for students.
Since then, we updated to a much more recent kernel, so this has been fixed in the process.
